GET http://localhost:8080/backend
Accept: text/html

###

GET http://localhost:8080/saleman/dingding
Accept: application/json

###

POST http://localhost:8080/saleman/dior
Accept: application/json
Cache-Control: no-cache

{'SID':2,'SPassword':'dido123','SName':'dior'}

###

PUT http://localhost:8080/saleman/dior?SName=diorr
Accept: application/json
Cache-Control: no-cache

###

DELETE http://localhost:8080/saleman/diorr
Accept: application/json
Cache-Control: no-cache

###

GET http://localhost:8080/saleman/?pattern=all
Accept: application/json
Cache-Control: no-cache

###

GET http://localhost:8080/saleman/d?pattern=fuzzy
Accept: application/json
Cache-Control: no-cache

###
