<!DOCTYPE>
<html>
<head>
    <title>Welcome</title>
</head>
<body>
    <h2 style="text-align: center;">欢迎使用超市综合管理系统</h2>
    <br>
    <div style="align-self: center; align-content: baseline; margin-left: 15%; margin-right: 15%;">
        <ol>
            <li><a href="/goodMaintain">商品维护</a> </li>
            <li><a href="/cash">前台收银</a> </li>
            <li><a href="/backend">后台管理</a> </li>
        </ol>
    </div>
</body>
</html>